
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group1blog
  labels:
    app: group1blog
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: group1blog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: group1blog
    spec:
      containers:
      - image: 341014156608.dkr.ecr.eu-central-1.amazonaws.com/group1blog:latest
        imagePullPolicy: Always
        name: group1blog
        ports:
        - containerPort: 5000
          protocol: TCP
